// Standardized Error Codes
// Clients match on `code` instead of parsing `message` strings.

export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Store
  STORE_SUSPENDED: 'STORE_SUSPENDED',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  PLAN_EXPIRED: 'PLAN_EXPIRED',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  PRODUCT_UNPUBLISHED: 'PRODUCT_UNPUBLISHED',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_FULFILLED: 'ORDER_ALREADY_FULFILLED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',

  // Coupon
  INVALID_COUPON: 'INVALID_COUPON',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_USAGE_EXCEEDED: 'COUPON_USAGE_EXCEEDED',

  // Customer
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ALREADY_EXISTS: 'CUSTOMER_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',

  // Modifier
  MODIFIER_GROUP_NOT_FOUND: 'MODIFIER_GROUP_NOT_FOUND',

  // Review
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',

  // Upload
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Merchant/User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // SuperAdmin
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',

  // Wishlist
  WISHLIST_ITEM_EXISTS: 'WISHLIST_ITEM_EXISTS',

  // Cart
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];